Repository brazil-data-cube/lccs-db, pull requests merged in 2021-02, with the labels that each got.

#77 add index and uniqueConstraint in classification system ref #75
  .drone.yml
  lccs_db/alembic/d3db4a1a7f75_add_index.py
  lccs_db/models/class_mapping.py
  lccs_db/models/luc_class.py
  lccs_db/models/luc_classification_system.py
  lccs_db/models/style_formats.py
  lccs_db/models/styles.py
Labels: enhancement

#84 Minor improvement in documentation.
  MANIFEST.in
  README.rst
  docs/sphinx/conf.py
  docs/sphinx/configure.rst
  docs/sphinx/installation.rst
  docs/sphinx/usage.rst
  lccs_db/config.py
  lccs_db/models/base.py
  lccs_db/models/class_mapping.py
  lccs_db/models/luc_class.py
  lccs_db/models/luc_classification_system.py
  lccs_db/models/style_formats.py
  lccs_db/models/styles.py
  setup.py
  tests/scripts/test-class-system.sql
Labels: enhancement

#88 fixing discord-notify order
  .drone.yml
Labels: bug

#90 reviewing the model and tests ref #89 and ref #87
  .drone.yml
  docs/sphinx/usage.rst
  examples/create_class_system.py
  lccs_db/__init__.py
  lccs_db/__main__.py
  lccs_db/alembic/237031a776fb_revision_0_6.py
  lccs_db/cli.py
  lccs_db/models/class_mapping.py
  lccs_db/models/luc_class.py
  lccs_db/models/luc_classification_system.py
  lccs_db/models/styles.py
  lccs_db/scripts/default_class_systems.sql
  lccs_db/utils.py
  tests/conftest.py
  tests/test_ext.py
  tests/test_lccs_db.py
Labels: enhancement

#93 Final review for v0.6.0
  .drone.yml
  README.rst
  docs/sphinx/index.rst
  docs/sphinx/installation.rst
  docs/sphinx/usage.rst
  setup.py
  tests/conftest.py
Labels: release

#94 fixing mimetype and change version to 0.6 close #92
  docs/spec/lccs_database.png
  docs/spec/lccs_database.xml
  lccs_db/__init__.py
Labels: bug, enhancement

#95 removing id in default_class_systems
  lccs_db/scripts/default_class_systems.sql
Labels: bug

#96 Fix typo in README.rst
  README.rst
Labels: bug
